### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by greg6775** [Creeperman007/WarnBot#3]
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   bei MySql.Data.MySqlClient.NativeDriver.Open()
   bei MySql.Data.MySqlClient.Driver.Open()
   bei MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   bei MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   bei MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   bei MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   bei MySql.Data.MySqlClient.MySqlPool.GetConnection()
   bei MySql.Data.MySqlClient.MySqlConnection.Open()
   bei WarnBot.DBConnector.PermCheck(UInt64 user, UInt64 guild) in C:\Users\GregT\Downloads\WarnBot-master\WarnBot-master\source\WarnBot\DBConnector.cs:Zeile 224.
   bei WarnBot.Program.<MessageReceived>d__2.MoveNext() in C:\Users\GregT\Downloads\WarnBot-master\WarnBot-master\source\WarnBot\Program.cs:Zeile 65.

**Comment by fajnyCreeper** [comment]
So, first of all, you will need to have SQL server running on your machine (or remote), then you need to fill the credentials in `DBConnector.cs` - `host`, `username`, `pass` and `name` (DB name). Then you will need to go to your database and create tables using [this SQL script](https://github.com/Creeperman007/WarnBot/blob/master/scheme.sql)
